In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(
    filepath_or_buffer='data/nba.csv'
)

df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,2-Jun,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6-Jun,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,5-Jun,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,5-Jun,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,10-Jun,231,NaN,5000000.0

In [4]:
df.shape

(457, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    int64
 3   Position  457 non-null    object
 4   Age       457 non-null    int64
 5   Height    457 non-null    object
 6   Weight    457 non-null    int64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(1), int64(3), object(5)
memory usage: 32.3+ KB

In [11]:
# En değerli takım kim
df_groupby_salary = (
    df.groupby(by='Team')
        .agg({
            'Salary': 'sum'
        })
        .sort_values(
            by='Salary',
            ascending=False
        )
        .head(1)
)
# $ 10,698,868.90 apply() ve lambda ile yapılacak
df_groupby_salary['Salary'] = df_groupby_salary['Salary'].apply(lambda x: f'$ {x:,.2f}')
df_groupby_salary

                               Salary
Team
Cleveland Cavaliers  $ 106,988,689.00

In [8]:
df_groupby_team = (
    df.groupby(by='Team')
        .agg({
            'Age': 'mean'
        })
        .sort_values(
            by='Age',
            ascending=False
        )
)

# Hint: apply() araştır ve lambda ile yapın. Age sütunundaki bilgilerin noktadan sonra 2 hanesi alınsın
df_groupby_team['Age'] = df_groupby_team['Age'].apply(lambda x: f'{x:.2f}')

df_groupby_team

                          Age
Team
San Antonio Spurs       31.60
Dallas Mavericks        29.73
Cleveland Cavaliers     29.53
Los Angeles Clippers    29.47
Miami Heat              28.93
Memphis Grizzlies       28.39
Atlanta Hawks           28.20
Washington Wizards      27.87
Golden State Warriors   27.67
Los Angeles Lakers      27.53
Chicago Bulls           27.40
Oklahoma City Thunder   27.07
New York Knicks         27.00
New Orleans Pelicans    26.89
Houston Rockets         26.87
Sacramento Kings        26.80
Indiana Pacers          26.40
Minnesota Timberwolves  26.36
Detroit Pistons         26.20
Toronto Raptors         26.13
Charlotte Hornets       26.13
Phoenix Suns            25.87
Denver Nuggets          25.73
Brooklyn Nets           25.60
Orlando Magic           25.07
Portland Trail Blazers  25.07
Boston Celtics          24.73
Philadelphia 76ers      24.60
Milwaukee Bucks         24.56
Utah Jazz               24.47

In [ ]:
df_college = (
    df.groupby(by='College')
        .agg({
            'Salary': 'mean'
        })
        .sort_values(
            by='Salary',
            ascending=False
        )
        .head(10)
)

df_college['College'] = df_college.index
df_college.reset_index(drop=True, inplace=True)
df_college['Salary'] = df_college['Salary'].apply(lambda x: f'$ {x:,.2f}')
df_college

            Salary           College
0  $ 18,907,726.00          Oklahoma
1  $ 18,671,659.00    Louisiana Tech
2  $ 16,407,500.00   San Diego State
3  $ 11,981,288.80         Marquette
4  $ 11,778,758.67         Texas A&M
5  $ 11,453,661.00           Memphis
6  $ 11,370,786.00          Davidson
7  $ 11,235,955.00    Morehead State
8  $ 11,000,500.00  Washington State
9  $ 10,676,908.33      Georgia Tech

In [20]:
# Custom Function yazalım
# Name sütunun bulunan bilgiler içerisinde "and" ifadesi geçen satırları filtereleyen bir fonksiyon yazalım
def str_find(name: str, prefix: str = 'and') -> bool:
    if prefix.lower() in name.lower():
        return True
    else:
        return False

df[
    df['Name'].apply(str_find)
]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
2,John Holland,Boston Celtics,30,SG,27,5-Jun,205,Boston University,NaN
46,Elton Brand,Philadelphia 76ers,42,PF,37,9-Jun,254,Duke,NaN
52,Carl Landry,Philadelphia 76ers,7,PF,32,9-Jun,248,Purdue,6500000.0
76,Leandro Barbosa,Golden State Warriors,19,SG,33,3-Jun,194,NaN,2500000.0
78,Andrew Bogut,Golden State Warriors,12,C,31,Jul-00,260,Utah,13800000.0
83,Andre Iguodala,Golden State Warriors,9,SF,32,6-Jun,215,Arizona,11710456.0
87,Brandon Rush,Golden State Warriors,4,SF,30,6-Jun,220,Kansas,1270964.0
90,Anderson Varejao,Golden State Warriors,18,PF,33,11-Jun,273,NaN,289755.0
94,Branden Dawson,Los Angeles Clippers,22,SF,23,6-Jun,225,Michigan State,525093.0
98,DeAndre Jordan,Los Angeles Clippers,6,C,27,11-Jun,265,Texas A&M,19689000.0
106,Brandon Bass,Los Angeles Lakers,2,PF,31,8-Jun,250,LSU,3000000.0
115,Julius Randle,Los Angeles Lakers,30,PF,21,9-Jun,250,Kentucky,3132240.0
124,Tyson Chandler,Phoenix Suns,4,C,33,1-Jul,240,NaN,13000000.0
127,Brandon Knight,Phoenix Suns,3,PG,24,3-Jun,189,Kentucky,13500000.0
137,James Anderson,Sacramento Kings,5,SG,27,6-Jun,213,Oklahoma State,1015421.0
149,Eric Moreland,Sacramento Kings,25,PF,24,10-Jun,238,Oregon State,845059.0
188,Andre Drummond,Detroit Pistons,0,C,22,11-Jun,279,Connecticut,3272091.0
227,Justin Anderson,Dallas Mavericks,1,SG,22,6-Jun,228,Virginia,1449000.0
238,Chandler Parsons,Dallas Mavericks,25,SF,27,10-Jun,230,Florida,15361500.0
248,Andrew Goudelock,Houston Rockets,0,PG,27,3-Jun,200,Charleston,200600.0
259,Chris Andersen,Memphis Grizzlies,7,PF,37,10-Jun,245,Blinn College,5000000.0
271,Zach Randolph,Memphis Grizzlies,50,PF,34,9-Jun,260,Michigan State,9638555.0
274,Brandan Wright,Memphis Grizzlies,34,PF,28,10-Jun,210,North Carolina,5464000.0
276,Ryan Anderson,New Orleans Pelicans,33,PF,28,10-Jun,240,California,8500000.0
291,Orlando Johnson,New Orleans Pelicans,0,SG,27,5-Jun,220,UC Santa Barbara,55722.0
295,Kyle Anderson,San Antonio Spurs,1,SF,22,9-Jun,230,UCLA,1142880.0
304,Andre Miller,San Antonio Spurs,24,PG,40,3-Jun,200,Utah,250750.0
359,Brandon Jennings,Orlando Magic,55,PG,26,1-Jun,169,NaN,8344497.0
362,Andrew Nicholson,Orlando Magic,44,PF,26,9-Jun,250,St. Bonaventure,2380593.0
368,Alan Anderson,Washington Wizards,6,SG,33,6-Jun,220,Michigan State,4000000.0
386,Wilson Chandler,Denver Nuggets,21,SF,29,8-Jun,225,DePaul,10449438.0
411,Andrew Wiggins,Minnesota Timberwolves,22,SG,21,8-Jun,199,Kansas,5758680.0
415,Randy Foye,Oklahoma City Thunder,6,SG,32,4-Jun,213,Villanova,3135000.0
423,Andre Roberson,Oklahoma City Thunder,21,SG,24,7-Jun,210,Colorado,1210800.0
427,Cliff Alexander,Portland Trail Blazers,34,PF,20,8-Jun,240,Kansas,525093.0