In [11]:
import pandas as pd

In [12]:
df = pd.read_csv(
    filepath_or_buffer='data/youtube-ing.csv'
)

df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...

In [13]:
df.shape

(38916, 16)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38916 entries, 0 to 38915
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                38916 non-null  object
 1   trending_date           38916 non-null  object
 2   title                   38916 non-null  object
 3   channel_title           38916 non-null  object
 4   category_id             38916 non-null  int64
 5   publish_time            38916 non-null  object
 6   tags                    38916 non-null  object
 7   views                   38916 non-null  int64
 8   likes                   38916 non-null  int64
 9   dislikes                38916 non-null  int64
 10  comment_count           38916 non-null  int64
 11  thumbnail_link          38916 non-null  object
 12  comments_disabled       38916 non-null  bool
 13  ratings_disabled        38916 non-null  bool
 14  video_error_or_removed  38916 non-null  bool
 15  description             38304 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 4.0+ MB

In [15]:
df.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'],
      dtype='object')

In [16]:
df.drop(
    columns=['thumbnail_link', 'comments_disabled', 'ratings_disabled', 'video_error_or_removed', 'description'],
    axis=1,
    inplace=True
)

df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30

In [17]:
(
    df.groupby(by='title')
        .agg({
            'views': ['sum', 'mean'],
            'likes': ['sum', 'mean'],
            'dislikes': ['sum', 'mean'],
            'comment_count': ['sum', 'mean']
        })
)

                                                       views                \
                                                         sum          mean
title
#21 How to go FAST!!! Coaching famous youtuber ...     47358  1.578600e+04
#ConanHaiti Preview: Haitians Roast Trump  - CO...   5953602  4.579694e+05
#GameOn - 88 Seconds of Video Games                  4691181  4.264710e+05
#KIISCampus Surprise with BTS | On Air with Rya...   1817099  1.514249e+05
#Laurel? #Yanny? Or...                               9875181  6.583454e+05
...                                                      ...           ...
인피니트(INFINITE) Tell Me Teaser #D-6. SUNGKYU           121549  1.215490e+05
청하 (CHUNGHA) - Roller Coaster MV                    39792610  2.842329e+06
한국 컵라면+소주를 처음 먹어본 동계올림픽 전설들의 반응!                    46211536  1.320330e+06
🔥  'Avengers: Infinity War' Cast Answer Your Bu...   9432999  8.575454e+05
🔥  The 'Avengers: Infinity War' Cast Play ‘HOT ...   6175569  6.175569e+05

                                                      likes                 \
                                                        sum           mean
title
#21 How to go FAST!!! Coaching famous youtuber ...     2052     684.000000
#ConanHaiti Preview: Haitians Roast Trump  - CO...   135580   10429.230769
#GameOn - 88 Seconds of Video Games                  136912   12446.545455
#KIISCampus Surprise with BTS | On Air with Rya...   117440    9786.666667
#Laurel? #Yanny? Or...                               190239   12682.600000
...                                                     ...            ...
인피니트(INFINITE) Tell Me Teaser #D-6. SUNGKYU           16980   16980.000000
청하 (CHUNGHA) - Roller Coaster MV                    1935927  138280.500000
한국 컵라면+소주를 처음 먹어본 동계올림픽 전설들의 반응!                     809687   23133.914286
🔥  'Avengers: Infinity War' Cast Answer Your Bu...   183317   16665.181818
🔥  The 'Avengers: Infinity War' Cast Play ‘HOT ...   126805   12680.500000

                                                   dislikes               \
                                                        sum         mean
title
#21 How to go FAST!!! Coaching famous youtuber ...       24     8.000000
#ConanHaiti Preview: Haitians Roast Trump  - CO...    19709  1516.076923
#GameOn - 88 Seconds of Video Games                    2112   192.000000
#KIISCampus Surprise with BTS | On Air with Rya...      419    34.916667
#Laurel? #Yanny? Or...                                91964  6130.933333
...                                                     ...          ...
인피니트(INFINITE) Tell Me Teaser #D-6. SUNGKYU              30    30.000000
청하 (CHUNGHA) - Roller Coaster MV                      25640  1831.428571
한국 컵라면+소주를 처음 먹어본 동계올림픽 전설들의 반응!                      14701   420.028571
🔥  'Avengers: Infinity War' Cast Answer Your Bu...     2101   191.000000
🔥  The 'Avengers: Infinity War' Cast Play ‘HOT ...     1497   149.700000

                                                   comment_count
                                                             sum         mean
title
#21 How to go FAST!!! Coaching famous youtuber ...           422   140.666667
#ConanHaiti Preview: Haitians Roast Trump  - CO...         21484  1652.615385
#GameOn - 88 Seconds of Video Games                         8384   762.181818
#KIISCampus Surprise with BTS | On Air with Rya...          8052   671.000000
#Laurel? #Yanny? Or...                                     55926  3728.400000
...                                                          ...          ...
인피니트(INFINITE) Tell Me Teaser #D-6. SUNGKYU                 1158  1158.000000
청하 (CHUNGHA) - Roller Coaster MV                           95850  6846.428571
한국 컵라면+소주를 처음 먹어본 동계올림픽 전설들의 반응!                           79635  2275.285714
🔥  'Avengers: Infinity War' Cast Answer Your Bu...          6065   551.363636
🔥  The 'Avengers: Infinity War' Cast Play ‘HOT ...          4609   460.900000

[3369 rows x 8 columns]

In [18]:
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30
...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933
38912,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330
38913,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988
38914,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766
38915,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423

# Feature Crafting

In [19]:
# Task: "tags" sütununda ki veriler parçalanıp sayılarak "tag_count" isimli yeni bir sütuna yazdırılacak
# Path I
# def calculate_tags(tag: str) -> int:
#     return len(tag.split('|'))

# df['tag_count'] = df['tags'].apply(calculate_tags)

# df[['title', 'tags', 'tag_count']]

In [ ]:
# Path II
df['tag_count'] = df['tags'].apply(lambda x: len(x.split('|')))

df[['title', 'tags', 'tag_count']]

,title,tags,tag_count
0,John Lewis Christmas Ad 2017 - #MozTheMonster,"christmas|""john lewis christmas""|""john lewis""|...",9
1,Taylor Swift: …Ready for It? (Live) - SNL,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",36
2,Eminem - Walk On Water (Audio) ft. Beyoncé,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",6
3,Goals from Salford City vs Class of 92 and Fri...,"Salford City FC|""Salford City""|""Salford""|""Clas...",9
4,Dashcam captures truck's near miss with child ...,[none],1
...,...,...,...
38911,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",4
38912,Jacob Sartorius - Up With It (Official Music V...,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",41
38913,Anne-Marie - 2002 [Official Video],"anne|""marie""|""anne-marie""|""2002""|""two thousand...",17
38914,Eleni Foureira - Fuego - Cyprus - LIVE - First...,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",8
38915,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",18

In [21]:
# en yüksek tag_count sahip 10 içerik
df.sort_values(
    by='tag_count',
    ascending=False
).head(10)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,tag_count
21370,xIZPbhq37WQ,18.02.03,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1798530,21843,282,1903,78
19528,xIZPbhq37WQ,18.21.02,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1660313,21700,282,1888,78
19330,xIZPbhq37WQ,18.20.02,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1649398,21699,281,1884,78
19732,xIZPbhq37WQ,18.22.02,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1671643,21711,282,1887,78
20549,xIZPbhq37WQ,18.26.02,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1733831,21773,282,1902,78
21161,xIZPbhq37WQ,18.01.03,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1788453,21840,282,1904,78
20349,xIZPbhq37WQ,18.25.02,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1723105,21762,282,1900,78
20147,xIZPbhq37WQ,18.24.02,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1700881,21745,282,1899,78
19137,xIZPbhq37WQ,18.19.02,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1626435,21685,281,1874,78
20956,xIZPbhq37WQ,18.28.02,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),특이한동물채널,15,2018-02-01T13:33:30.000Z,"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",1766758,21830,282,1906,78

In [23]:
# tag_count 30'dan büyük olan içerikleri yazdırın
df.query('tag_count > 30')[['title', 'tags', 'tag_count']].sort_values(by='tag_count', ascending=False)

,title,tags,tag_count
19932,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
20147,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
19528,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
20956,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
20549,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
...,...,...,...
35546,The 'Avengers: Infinity War' Cast Reveal Who T...,"PopBuzz|""Avengers""|""Infinity War""|""Marvel""|""To...",31
16618,ADULTS REACT TO KARMA IS A BITCH CHALLENGE,"karma is a bitch challenge|""karma's a bitch ch...",31
16635,The Story of Tetris | Gaming Historian,"Tetris|""Alexey Pajitnov""|""Story of Tetris""|""Va...",31
16636,SHOULD I HAVE A HOME BIRTH?,"jamie and nikki|""family vlog""|""daily vlog""|""be...",31
16657,The Crown | Growing Up Royal | Netflix,"Netflix|""Trailer""|""Netflix Original Series""|""N...",31

In [27]:
# (likes / likes + dislike) formülü üzerinden hesaplanarak like_avg sütununa yazalım
def like_dislike_avg(likes: pd.Series, dislikes: pd.Series) -> list:
    like_list = list(likes)
    dislike_list = list(dislikes)

    combine_list = list(
        zip(like_list, dislike_list)
    )

    avg_list = []

    for like, dislike in combine_list:
        if like + dislike == 0:
            avg_list.append(0)
        else:
            avg = like / (like + dislike)
            avg_list.append(avg)
    
    return avg_list

df['like_avg'] = like_dislike_avg(likes=df['likes'], dislikes=df['dislikes'])

df[['title', 'likes', 'dislikes', 'like_avg']]

,title,likes,dislikes,like_avg
0,John Lewis Christmas Ad 2017 - #MozTheMonster,55681,10247,0.844573
1,Taylor Swift: …Ready for It? (Live) - SNL,25561,2294,0.917645
2,Eminem - Walk On Water (Audio) ft. Beyoncé,787420,43420,0.947740
3,Goals from Salford City vs Class of 92 and Fri...,193,12,0.941463
4,Dashcam captures truck's near miss with child ...,30,2,0.937500
...,...,...,...,...
38911,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,268088,12783,0.954488
38912,Jacob Sartorius - Up With It (Official Music V...,61998,13781,0.818142
38913,Anne-Marie - 2002 [Official Video],394830,8892,0.977975
38914,Eleni Foureira - Fuego - Cyprus - LIVE - First...,151870,45875,0.768009
38915,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,18271,274,0.985225

In [33]:
# kanalların like avg nedir?
(
    df.groupby(by='channel_title')
        .agg({
            'like_avg': 'mean',
            'comment_count': 'sum',
            'views': 'sum'
        })
        .sort_values(
            by='views',
            ascending=False
        ).head(10)
)

                      like_avg  comment_count       views
channel_title
NickyJamTV            0.919090        2947640  8516190092
Ozuna                 0.944864        2985745  8305198063
Bad Bunny             0.954874        6127443  6891280759
DrakeVEVO             0.974120        9225778  6581834413
ChildishGambinoVEVO   0.941987       15441941  6101309613
Flow La Movie         0.953427        2003208  5151438858
ArianaGrandeVevo      0.961762        7869276  4107436350
Marvel Entertainment  0.970195       11525772  3993421220
jypentertainment      0.961262       15703519  3624070589
Ed Sheeran            0.978558        4434316  3589056783